### ISSUE TITLE
Add an `apertium-xxx` topic

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-fin-deu#1]
Without an `apertium-incubator`, `apertium-nursery`, etc. topic, this repo will not be collected into any metarepo or displayed in the source browser: https://apertium.github.io/apertium-on-github/source-browser.html.

**Comment by flammie** [comment]
It seems I don't have (write) access to the topics... can you add one? I don't really care about those incubators nurseries stagings, so any one is fine by me.

**Comment by sushain97** [comment]
Do you mind trying again? I upped your access to this repo to admin level. @ftyers probably has more thoughts on which topic.

**Comment by flammie** [comment]
Worked, I put nursings for now.

**Comment by sushain97** [comment]
Sounds good. As a note, it won't be picked up until your next push due to limitations of GitHub's web hooks.
